In [13]:
import numpy as np
import sklearn.datasets as dt
from sklearn.model_selection import train_test_split as tts
from sklearn.metrics import accuracy_score
from sklearn.datasets import make_blobs, make_classification

In [14]:
# X, y = dt.load_iris(return_X_y=True)
X, y = make_classification(n_samples=500, n_features=38, n_redundant=0, n_informative=4, n_classes=2, n_clusters_per_class=1)
X_train, X_test, y_train, y_test = tts(X, y, test_size=0.2, random_state=0)

In [15]:
from LVQ.lvq import LVQ3

In [16]:
lvq = LVQ3(epsilon=0.2, epoch=200)

In [17]:
model = lvq.fit(X_train, y_train)

In [18]:
X.shape[1]

38

In [19]:
lvq.weight

array([[-0.36531064,  0.86489859, -0.39097678,  0.37235634,  0.37378254,
        -0.01157905, -0.97764682, -0.31486147, -0.26603832,  0.08116944,
         0.09984649, -0.02096887, -0.56694473, -0.1318667 ,  0.05993801,
         1.6772551 , -0.48779384,  0.60743425,  0.04437447, -0.16863458,
        -0.36387132,  1.16051592, -0.26027367, -0.5708659 ,  1.09301909,
        -0.64803609,  0.71958136, -0.86675751,  0.26205591, -0.53541001,
         0.14823599,  0.31067514, -2.23389558,  0.32782902,  4.38576204,
         0.46955988,  0.71656774,  0.01068257],
       [ 0.44033039, -0.49839771,  1.27273259,  0.49909341,  0.50391801,
         0.14284496, -0.54281552,  0.12895198,  0.26924612, -0.55964737,
         0.30663172,  0.40311491,  0.44158284, -0.14384687, -0.26869482,
        -1.36854922, -0.34757566,  0.81990067, -0.06993255,  0.00707279,
        -0.47918374, -0.39137578,  0.20475636, -0.39012261, -0.33114004,
         1.09132451,  0.00654261,  1.19312576, -0.33931057,  0.46705286,
   

In [20]:
result = lvq.predict(X_test)

In [21]:
X[:4]

array([[ 1.11802225,  0.24027562,  0.2081602 , -0.56752487, -0.91024946,
        -0.22739502, -1.73491142,  1.15954015, -0.7409227 ,  0.16301498,
         0.87876599, -0.04905042,  0.40548027,  0.90099347,  1.09485021,
         0.12957916,  2.33838261,  0.9243    ,  1.98624817, -1.56407257,
        -0.48045692,  0.65560829, -1.34656487,  0.13638447, -0.47229672,
         0.48175155, -1.07237261,  1.89428555, -2.65664561,  1.54938075,
        -0.441103  , -0.55482729,  1.44327381,  0.84414448, -1.11487745,
         0.17016374, -2.05710662, -1.13557497],
       [-1.19324474, -0.51987907,  0.20703706,  0.47271562,  0.62405988,
        -1.52072494, -0.47169727, -0.69146861,  0.10798524,  0.55905217,
        -0.50935354, -0.61245749, -0.7221654 ,  0.66281953, -0.13957258,
        -0.23564363,  1.45844463, -0.6336255 , -0.31970842,  0.13659868,
        -0.54990734,  0.47663729,  0.83250743,  0.61879877,  0.44505886,
         0.79315527, -2.62246856,  1.13802487,  0.81437475,  1.33643066,
   

In [22]:
y_test

array([0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0])

In [23]:
result

array([0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0])

In [24]:
accuracy_score(result, y_test)

0.96