In [40]:
import numpy as np
import pandas as pd
import sklearn.datasets as dt
from sklearn.model_selection import train_test_split as tts
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from LVQ.lvq import LVQ3
from sklearn.preprocessing import OneHotEncoder

In [41]:
X, y = pd.read_csv("../data/raw/train_values.csv"), pd.read_csv("../data/raw/train_labels.csv")

In [42]:
X

building_id  geo_level_1_id  geo_level_2_id  geo_level_3_id  \
0           1020144              10             804            1371   
1            199685              25             211            5071   
2           1038433              22             816           12104   
3            461920               6             449            3741   
4            957027              20             254            5266   
...             ...             ...             ...             ...   
208475       788768              22             165           10190   
208476       490379              27             269            5197   
208477       294228              26            1259           10829   
208478       464117               7             258            1869   
208479       652585              26             366            2116   

        count_floors_pre_eq  age  area_percentage  height_percentage  \
0                         2    5                7                  6   
1                         2   25                9                  4   
2                         2   10                5                  4   
3                         1   10                8                  3   
4                         2   10               10                  6   
...                     ...  ...              ...                ...   
208475                    2   30                5                  4   
208476                    3   80                5                  6   
208477                    1   10                4                  6   
208478                    1   15                6                  3   
208479                    2   20                8                  5   

       land_surface_condition foundation_type  ...  \
0                           t               r  ...   
1                           n               r  ...   
2                           t               r  ...   
3                           t               r  ...   
4                           n               w  ...   
...                       ...             ...  ...   
208475                      t               r  ...   
208476                      t               r  ...   
208477                      t               r  ...   
208478                      t               r  ...   
208479                      o               r  ...   

       has_secondary_use_agriculture has_secondary_use_hotel  \
0                                  0                       0   
1                                  0                       0   
2                                  0                       0   
3                                  0                       0   
4                                  1                       0   
...                              ...                     ...   
208475                             0                       0   
208476                             0                       0   
208477                             0                       0   
208478                             0                       0   
208479                             0                       0   

       has_secondary_use_rental has_secondary_use_institution  \
0                             0                             0   
1                             0                             0   
2                             0                             0   
3                             0                             0   
4                             0                             0   
...                         ...                           ...   
208475                        0                             0   
208476                        0                             0   
208477                        0                             0   
208478                        0                             0   
208479                        0                             0   

       has_secondary_use_school  has_secondary_use_industry  \
0                           

In [43]:
df = pd.merge(X, y,left_on="building_id", right_on="building_id").iloc[:,1:]

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 208480 entries, 0 to 208479
Data columns (total 39 columns):
 #   Column                                  Non-Null Count   Dtype 
---  ------                                  --------------   ----- 
 0   geo_level_1_id                          208480 non-null  int64 
 1   geo_level_2_id                          208480 non-null  int64 
 2   geo_level_3_id                          208480 non-null  int64 
 3   count_floors_pre_eq                     208480 non-null  int64 
 4   age                                     208480 non-null  int64 
 5   area_percentage                         208480 non-null  int64 
 6   height_percentage                       208480 non-null  int64 
 7   land_surface_condition                  208480 non-null  object
 8   foundation_type                         208480 non-null  object
 9   roof_type                               208480 non-null  object
 10  ground_floor_type                       208480 non-null 

In [45]:
df.iloc[:,-1]

0         2
1         2
2         2
3         2
4         3
         ..
208475    1
208476    2
208477    3
208478    3
208479    2
Name: damage_grade, Length: 208480, dtype: int64

In [46]:
from imblearn.over_sampling import SMOTENC
sm = SMOTENC(random_state=42, categorical_features=[7,8,9,10,11,12,13,25])

In [47]:
X, y = df.iloc[:,:-1], df.iloc[:,-1]

In [49]:
X_res, y_res = sm.fit_resample(X, y)

In [50]:
X_res

geo_level_1_id  geo_level_2_id  geo_level_3_id  count_floors_pre_eq  \
0                   10             804            1371                    2   
1                   25             211            5071                    2   
2                   22             816           12104                    2   
3                    6             449            3741                    1   
4                   20             254            5266                    2   
...                ...             ...             ...                  ...   
356017               5             598            5662                    2   
356018              27             533            5800                    3   
356019              21             313           11708                    3   
356020               6            1126           11865                    1   
356021               4              55            2653                    2   

        age  area_percentage  height_percentage land_surface_condition  \
0         5                7                  6                      t   
1        25                9                  4                      n   
2        10                5                  4                      t   
3        10                8                  3                      t   
4        10               10                  6                      n   
...     ...              ...                ...                    ...   
356017  995                6                  8                      t   
356018   15               19                  9                      t   
356019   15                5                  5                      t   
356020   25                6                  3                      t   
356021    5                5                  5                      t   

       foundation_type roof_type  ... has_secondary_use_agriculture  \
0                    r         n  ...                             0   
1                    r         q  ...                             0   
2                    r         q  ...                             0   
3                    r         q  ...                             0   
4                    w         q  ...                             1   
...                ...       ...  ...                           ...   
356017               r         n  ...                             0   
356018               r         n  ...                             0   
356019               r         q  ...                             0   
356020               r         n  ...                             0   
356021               r         q  ...                             0   

       has_secondary_use_hotel has_secondary_use_rental  \
0                            0                        0   
1                            0                        0   
2                            0                        0   
3                            0                        0   
4                            0                        0   
...                        ...                      ...   
356017                       0                        0   
356018                       0                        0   
356019                       0                        0   
356020                       0                        0   
356021                       0                        0   

       has_secondary_use_institution  has_secondary_use_school  \
0                                  0                         0   
1                                  0                         0   
2                                  0                         0   
3                                  0                         0   
4                                  0                         0   
...                              ...                       ...   
356017                             0                         0   
356018                             0                         0   
356019        

In [51]:
y_res

0         2
1         2
2         2
3         2
4         3
         ..
356017    3
356018    3
356019    3
356020    3
356021    3
Name: damage_grade, Length: 356022, dtype: int64

In [52]:
np.unique(y_res, return_counts=True)

(array([1, 2, 3]), array([118674, 118674, 118674]))

In [53]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 208480 entries, 0 to 208479
Data columns (total 38 columns):
 #   Column                                  Non-Null Count   Dtype 
---  ------                                  --------------   ----- 
 0   geo_level_1_id                          208480 non-null  int64 
 1   geo_level_2_id                          208480 non-null  int64 
 2   geo_level_3_id                          208480 non-null  int64 
 3   count_floors_pre_eq                     208480 non-null  int64 
 4   age                                     208480 non-null  int64 
 5   area_percentage                         208480 non-null  int64 
 6   height_percentage                       208480 non-null  int64 
 7   land_surface_condition                  208480 non-null  object
 8   foundation_type                         208480 non-null  object
 9   roof_type                               208480 non-null  object
 10  ground_floor_type                       208480 non-null 

In [54]:
col = X_res.select_dtypes(include="object")
enc = OneHotEncoder(sparse_output=False, handle_unknown="infrequent_if_exist", drop="if_binary")
val = pd.DataFrame(enc.fit_transform(col))
fin = X_res.select_dtypes(exclude="object")

In [55]:
val

0    1    2    3    4    5    6    7    8    9   ...   28   29   30  \
0       0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0   
1       1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   
2       0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   
3       0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   
4       1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  ...  0.0  0.0  0.0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
356017  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0   
356018  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0   
356019  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   
356020  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  ...  0.0  0.0  0.0   
356021  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  ...  0.0  0.0  0.0   

         31   32   33   34   35   36   37  
0       0.0  0.0  0.0  0.0  0.0  1.0  0.0  
1       0.0  0.0  0.0  0.0  0.0  1.0  0.0  
2       0.0  0.0  0.0  0.0  0.0  1.0  0.0  
3       1.0  0.0  0.0  0.0  0.0  1.0  0.0  
4       0.0  0.0  0.0  0.0  0.0  1.0  0.0  
...     ...  ...  ...  ...  ...  ...  ...  
356017  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
356018  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
356019  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
356020  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
356021  0.0  0.0  0.0  0.0  0.0  1.0  0.0  

[356022 rows x 38 columns]

In [56]:
result = pd.concat([fin, val], axis=1)
result

geo_level_1_id  geo_level_2_id  geo_level_3_id  count_floors_pre_eq  \
0                   10             804            1371                    2   
1                   25             211            5071                    2   
2                   22             816           12104                    2   
3                    6             449            3741                    1   
4                   20             254            5266                    2   
...                ...             ...             ...                  ...   
356017               5             598            5662                    2   
356018              27             533            5800                    3   
356019              21             313           11708                    3   
356020               6            1126           11865                    1   
356021               4              55            2653                    2   

        age  area_percentage  height_percentage  has_superstructure_adobe_mud  \
0         5                7                  6                             0   
1        25                9                  4                             0   
2        10                5                  4                             0   
3        10                8                  3                             0   
4        10               10                  6                             0   
...     ...              ...                ...                           ...   
356017  995                6                  8                             0   
356018   15               19                  9                             1   
356019   15                5                  5                             0   
356020   25                6                  3                             0   
356021    5                5                  5                             0   

        has_superstructure_mud_mortar_stone  has_superstructure_stone_flag  \
0                                         1                              0   
1                                         1                              0   
2                                         1                              0   
3                                         1                              0   
4                                         1                              0   
...                                     ...                            ...   
356017                                    0                              0   
356018                                    0                              0   
356019                                    1                              0   
356020                                    1                              0   
356021                                    1                              0   

        ...   28   29   30   31   32   33   34   35   36   37  
0       ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
1       ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
2       ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
3       ...  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  
4       ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  
356017  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
356018  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
356019  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
356020  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
356021  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  

[356022 rows x 68 columns]

In [57]:
X_scaled = StandardScaler().fit_transform(result.values)
X_scaled

array([[-0.59579677,  0.27274631, -1.33331424, ..., -0.06932823,
         0.20466196, -0.09120368],
       [ 1.25505728, -1.13739869, -0.32425674, ..., -0.06932823,
         0.20466196, -0.09120368],
       [ 0.88488647,  0.30128213,  1.59377067, ..., -0.06932823,
         0.20466196, -0.09120368],
       ...,
       [ 0.7614962 , -0.89484424,  1.48577424, ..., -0.06932823,
         0.20466196, -0.09120368],
       [-1.08935786,  1.03845743,  1.52859101, ..., -0.06932823,
         0.20466196, -0.09120368],
       [-1.3361384 , -1.50836432, -0.98368945, ..., -0.06932823,
         0.20466196, -0.09120368]])

In [73]:
ty = y_res - 1
X_train, X_test, y_train, y_test = tts(X_scaled, ty, test_size=0.3, shuffle=True, random_state=15)

In [76]:
np.unique(y_train, return_counts=True)

(array([0, 1, 2]), array([83236, 83047, 82932]))

In [74]:
y_train

349132    2
293411    0
339938    2
28276     1
12582     2
         ..
104832    2
180087    1
199301    1
270220    0
269768    0
Name: damage_grade, Length: 249215, dtype: int64

In [84]:
output_size = np.unique(ty).shape[0]
input_size = X_train.shape[1]

one = LVQ3(input_size, output_size, random_state=21, epoch=100, alpha=0.65, beta=0.35, m=0.2,epsilon=0.3)
one.fit(X_train, y_train)


In [85]:
one.weight

array([[-8.17914247e-01,  1.11062055e-01,  8.15728408e-01,
         5.43095686e-01, -2.63950786e-01,  1.92148665e-01,
         1.16851082e+00, -3.71454421e-01, -8.26579099e-01,
        -1.58988779e-01, -1.22133779e-01, -3.45842006e-01,
         2.21310867e+00, -4.43053121e-01, -9.86514324e-02,
         2.85789573e+00, -1.55359716e-01, -1.01932881e-01,
        -2.66698938e-01,  3.05729132e+00,  9.04394201e-01,
         3.30042451e-01, -8.86557928e-02, -1.82312879e-02,
        -7.41950040e-03, -2.07402348e-02, -1.03500400e-02,
         6.85488689e+01, -1.07312994e-02, -6.36188958e-02,
        -3.54753850e-01, -1.63298539e-01,  3.97464205e-01,
        -8.25837247e-02,  2.22665876e+00, -1.22252125e+00,
        -2.58311777e-01, -1.39727281e-01, -9.87761471e-01,
        -3.96029043e-01,  1.93560286e+00, -1.11048475e+00,
        -3.38308033e-02,  1.52921785e+00, -2.94310070e-01,
        -5.82797250e-02, -4.83893404e-01, -6.18223805e-01,
         2.37612586e+00, -4.23474865e-01, -2.17463212e-0

In [86]:
y_train

349132    2
293411    0
339938    2
28276     1
12582     2
         ..
104832    2
180087    1
199301    1
270220    0
269768    0
Name: damage_grade, Length: 249215, dtype: int64

In [87]:
res

array([1, 1, 1, ..., 1, 1, 1])

In [91]:
np.unique(res, return_counts=True)

(array([0, 1]), array([     6, 106801]))

In [89]:
res = one.predict(X_test)
print(classification_report(res, y_test, zero_division=1))

              precision    recall  f1-score   support

           0       0.00      0.33      0.00         6
           1       1.00      0.33      0.50    106801
           2       0.00      1.00      0.00         0

    accuracy                           0.33    106807
   macro avg       0.33      0.56      0.17    106807
weighted avg       1.00      0.33      0.50    106807
