In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split as tts
from sklearn.metrics import accuracy_score, classification_report
from sklearn.preprocessing import StandardScaler
from LVQ.lvq import LVQ3

In [2]:
X, y = pd.read_csv("../data/raw/train_values.csv"), pd.read_csv("../data/raw/train_labels.csv")

In [3]:
X

building_id  geo_level_1_id  geo_level_2_id  geo_level_3_id  \
0           1020144              10             804            1371   
1            199685              25             211            5071   
2           1038433              22             816           12104   
3            461920               6             449            3741   
4            957027              20             254            5266   
...             ...             ...             ...             ...   
208475       788768              22             165           10190   
208476       490379              27             269            5197   
208477       294228              26            1259           10829   
208478       464117               7             258            1869   
208479       652585              26             366            2116   

        count_floors_pre_eq  age  area_percentage  height_percentage  \
0                         2    5                7                  6   
1                         2   25                9                  4   
2                         2   10                5                  4   
3                         1   10                8                  3   
4                         2   10               10                  6   
...                     ...  ...              ...                ...   
208475                    2   30                5                  4   
208476                    3   80                5                  6   
208477                    1   10                4                  6   
208478                    1   15                6                  3   
208479                    2   20                8                  5   

       land_surface_condition foundation_type  ...  \
0                           t               r  ...   
1                           n               r  ...   
2                           t               r  ...   
3                           t               r  ...   
4                           n               w  ...   
...                       ...             ...  ...   
208475                      t               r  ...   
208476                      t               r  ...   
208477                      t               r  ...   
208478                      t               r  ...   
208479                      o               r  ...   

       has_secondary_use_agriculture has_secondary_use_hotel  \
0                                  0                       0   
1                                  0                       0   
2                                  0                       0   
3                                  0                       0   
4                                  1                       0   
...                              ...                     ...   
208475                             0                       0   
208476                             0                       0   
208477                             0                       0   
208478                             0                       0   
208479                             0                       0   

       has_secondary_use_rental has_secondary_use_institution  \
0                             0                             0   
1                             0                             0   
2                             0                             0   
3                             0                             0   
4                             0                             0   
...                         ...                           ...   
208475                        0                             0   
208476                        0                             0   
208477                        0                             0   
208478                        0                             0   
208479                        0                             0   

       has_secondary_use_school  has_secondary_use_industry  \
0                           

In [4]:
df = pd.merge(X, y,left_on="building_id", right_on="building_id").iloc[:,1:]

In [5]:
# df.to_csv("../data/raw/train_data.csv")

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 208480 entries, 0 to 208479
Data columns (total 39 columns):
 #   Column                                  Non-Null Count   Dtype 
---  ------                                  --------------   ----- 
 0   geo_level_1_id                          208480 non-null  int64 
 1   geo_level_2_id                          208480 non-null  int64 
 2   geo_level_3_id                          208480 non-null  int64 
 3   count_floors_pre_eq                     208480 non-null  int64 
 4   age                                     208480 non-null  int64 
 5   area_percentage                         208480 non-null  int64 
 6   height_percentage                       208480 non-null  int64 
 7   land_surface_condition                  208480 non-null  object
 8   foundation_type                         208480 non-null  object
 9   roof_type                               208480 non-null  object
 10  ground_floor_type                       208480 non-null 

In [7]:
df.iloc[:,-1]

0         2
1         2
2         2
3         2
4         3
         ..
208475    1
208476    2
208477    3
208478    3
208479    2
Name: damage_grade, Length: 208480, dtype: int64

In [8]:
X, y = df.iloc[:,:-1], df.iloc[:,-1]

In [9]:
X.iloc[:,:7] = X.iloc[:,:7].astype("float")

/tmp/ipykernel_10481/2387548514.py:1: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  X.iloc[:,:7] = X.iloc[:,:7].astype("float")


In [10]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 208480 entries, 0 to 208479
Data columns (total 38 columns):
 #   Column                                  Non-Null Count   Dtype  
---  ------                                  --------------   -----  
 0   geo_level_1_id                          208480 non-null  float64
 1   geo_level_2_id                          208480 non-null  float64
 2   geo_level_3_id                          208480 non-null  float64
 3   count_floors_pre_eq                     208480 non-null  float64
 4   age                                     208480 non-null  float64
 5   area_percentage                         208480 non-null  float64
 6   height_percentage                       208480 non-null  float64
 7   land_surface_condition                  208480 non-null  object 
 8   foundation_type                         208480 non-null  object 
 9   roof_type                               208480 non-null  object 
 10  ground_floor_type                       2084

In [11]:
X

geo_level_1_id  geo_level_2_id  geo_level_3_id  count_floors_pre_eq  \
0                 10.0           804.0          1371.0                  2.0   
1                 25.0           211.0          5071.0                  2.0   
2                 22.0           816.0         12104.0                  2.0   
3                  6.0           449.0          3741.0                  1.0   
4                 20.0           254.0          5266.0                  2.0   
...                ...             ...             ...                  ...   
208475            22.0           165.0         10190.0                  2.0   
208476            27.0           269.0          5197.0                  3.0   
208477            26.0          1259.0         10829.0                  1.0   
208478             7.0           258.0          1869.0                  1.0   
208479            26.0           366.0          2116.0                  2.0   

         age  area_percentage  height_percentage land_surface_condition  \
0        5.0              7.0                6.0                      t   
1       25.0              9.0                4.0                      n   
2       10.0              5.0                4.0                      t   
3       10.0              8.0                3.0                      t   
4       10.0             10.0                6.0                      n   
...      ...              ...                ...                    ...   
208475  30.0              5.0                4.0                      t   
208476  80.0              5.0                6.0                      t   
208477  10.0              4.0                6.0                      t   
208478  15.0              6.0                3.0                      t   
208479  20.0              8.0                5.0                      o   

       foundation_type roof_type  ... has_secondary_use_agriculture  \
0                    r         n  ...                             0   
1                    r         q  ...                             0   
2                    r         q  ...                             0   
3                    r         q  ...                             0   
4                    w         q  ...                             1   
...                ...       ...  ...                           ...   
208475               r         n  ...                             0   
208476               r         q  ...                             0   
208477               r         n  ...                             0   
208478               r         q  ...                             0   
208479               r         n  ...                             0   

       has_secondary_use_hotel has_secondary_use_rental  \
0                            0                        0   
1                            0                        0   
2                            0                        0   
3                            0                        0   
4                            0                        0   
...                        ...                      ...   
208475                       0                        0   
208476                       0                        0   
208477                       0                        0   
208478                       0                        0   
208479                       0                        0   

       has_secondary_use_institution  has_secondary_use_school  \
0                                  0                         0   
1                                  0                         0   
2                                  0                         0   
3                                  0                         0   
4                                  0                         0   
...                              ...                       ...   
208475                             0                         0   
208476                             0                         0   
20

In [12]:
from prince import FAMD
famd = FAMD(n_components =24, n_iter = 100, copy=True, random_state = 201)

X_t = famd.fit_transform(X)

In [13]:
X_t

component        0         1          2         3         4         5   \
0         -1.701051 -3.000050  -2.044228  5.179376 -1.641714 -0.457770   
1         -4.309564 -2.507675  -2.193442 -2.617493 -1.636667 -0.327119   
2         -3.977083 -2.600835  -2.686598 -1.733000 -1.327434 -2.821173   
3         -1.720871  0.469089  -3.641277 -3.406394  3.505867  1.178325   
4         -3.523487  6.577175  22.226918 -7.553189 -4.212696 -8.171183   
...             ...       ...        ...       ...       ...       ...   
208475    -4.461848  0.238742  -0.735954 -2.028388 -1.794362 -0.910754   
208476    -2.381251 -4.217525  -1.092262 -0.399383 -1.553406 -2.127632   
208477    -3.066257  2.537775  -1.134772 -3.825351  1.743642 -0.105119   
208478    -2.572597 -0.301124  -3.120865 -3.591399  2.290917 -1.981141   
208479    -4.108119 -2.971069  -1.814708 -2.421412 -0.476931  0.563692   

component        6         7         8         9   ...        14        15  \
0          0.195021 -1.759314  5.259089  3.656198  ...  1.303162  1.258406   
1          2.021620  0.281315  0.169952  0.107093  ... -0.885311  0.617391   
2          1.717161  3.515148  1.285760  1.306363  ...  0.522013  0.458660   
3         -6.110034  0.078607  1.169644 -2.801277  ... -6.936840 -3.292731   
4          2.029656 -0.900409 -4.282358 -1.094962  ... -0.662094  2.915530   
...             ...       ...       ...       ...  ...       ...       ...   
208475     0.061090 -1.373690 -0.909744  0.533726  ...  1.054899  1.467030   
208476     0.886747  5.193587  2.025598  3.147709  ... -7.025852 -2.104677   
208477    -4.270846 -2.584460 -1.082667 -0.569282  ...  1.139079  0.892993   
208478    -2.663281  2.321769  1.073712  0.206704  ...  0.644068 -0.136356   
208479     0.149018 -4.456860  0.967941 -1.577584  ...  3.316166 -8.416624   

component        16        17        18        19        20        21  \
0         -0.531765  1.876886  2.351836 -2.126017  1.689252  1.533864   
1          0.943360 -0.836988 -0.870991  1.222009  2.394523 -2.709819   
2         -1.069290 -0.226129 -0.807389  0.041736  0.141348 -0.180756   
3          1.140881 -2.613134 -0.115012  5.219438  1.775137 -4.067345   
4          2.818005  0.590408 -1.693538  1.724616  3.141534 -2.242910   
...             ...       ...       ...       ...       ...       ...   
208475    -0.012222  0.631421  0.637616 -0.126554 -0.447467  1.150542   
208476     1.529800 -1.473126 -1.458080 -1.625334  0.581687 -0.601886   
208477     0.126387  1.217061  0.797612 -0.561971 -0.779601  1.421715   
208478    -0.937827  0.395847 -0.669239 -0.427823 -0.189338  0.103367   
208479    -4.025879  0.431147 -1.176793 -2.309327 -5.867522  4.057720   

component        22        23  
0         -0.464553  0.519011  
1         -1.844788  0.194157  
2         -0.731415 -0.127908  
3         -7.789231  0.256109  
4         -1.911997 -0.421602  
...             ...       ...  
208475     0.852503 -0.172424  
208476    -0.900110  0.288106  
208477     0.962994 -0.125764  
208478    -0.655218 -0.071902  
208479     0.947759  1.698226  

[208480 rows x 24 columns]

In [14]:
from imblearn.combine import SMOTETomek, SMOTEENN
cm = SMOTETomek(random_state=201)
# cm = SMOTEENN(random_state=20)

In [15]:
X_res, y_res = cm.fit_resample(X_t, y)

In [16]:
X_res

component        0         1         2          3         4         5   \
0         -1.701051 -3.000050 -2.044228   5.179376 -1.641714 -0.457770   
1         -4.309564 -2.507675 -2.193442  -2.617493 -1.636667 -0.327119   
2         -3.977083 -2.600835 -2.686598  -1.733000 -1.327434 -2.821173   
3         -3.992385 -3.115595 -1.830131  -2.374022 -0.543896  0.627794   
4          1.898713  5.260786 -2.488995  22.690547 -4.781668 -2.984109   
...             ...       ...       ...        ...       ...       ...   
329177    -3.827748 -3.315584 -2.839611  -0.910373  0.025599 -0.889777   
329178    -3.142781 -3.114843 -3.309449  -0.151284  2.303939  0.727335   
329179    -3.822957 -3.454365 -2.846388  -0.729386 -0.150355 -0.886296   
329180    -3.934012 -2.715741 -2.680783  -1.500949 -1.542368 -2.836434   
329181    -2.636712 -3.780442 -3.152173   1.384311  1.983806  1.722355   

component        6         7         8          9   ...        14        15  \
0          0.195021 -1.759314  5.259089   3.656198  ...  1.303162  1.258406   
1          2.021620  0.281315  0.169952   0.107093  ... -0.885311  0.617391   
2          1.717161  3.515148  1.285760   1.306363  ...  0.522013  0.458660   
3          0.231131 -4.448580  0.952272  -1.579381  ...  3.340802 -8.410943   
4          4.551011  6.163544 -6.858041 -17.570695  ...  7.779697 -9.452363   
...             ...       ...       ...        ...  ...       ...       ...   
329177    -1.302103 -0.352542  0.040079   0.410724  ...  0.950193  0.865164   
329178     3.135233 -1.028712 -0.306178  -0.788334  ...  3.393605 -0.898134   
329179    -1.131359 -0.328322  0.067758   0.427065  ...  0.960734  0.880909   
329180     1.926373  3.548349  1.316341   1.316761  ...  0.527505  0.485431   
329181     3.473639 -0.340924 -0.736643   0.344717  ... -0.350034 -1.060726   

component         16        17        18        19        20         21  \
0          -0.531765  1.876886  2.351836 -2.126017  1.689252   1.533864   
1           0.943360 -0.836988 -0.870991  1.222009  2.394523  -2.709819   
2          -1.069290 -0.226129 -0.807389  0.041736  0.141348  -0.180756   
3          -4.038321  0.429795 -1.168166 -2.287849 -5.862878   4.040551   
4          13.311720 -2.137756  5.684260  0.031427 -1.390358 -11.428665   
...              ...       ...       ...       ...       ...        ...   
329177     -0.477008  0.494394  0.281226  0.030949 -0.317044   0.654882   
329178     -0.676299  0.046214  0.180780 -2.598894 -0.380520   1.402215   
329179     -0.502859  0.463603  0.269361  0.045122 -0.309678   0.640148   
329180     -1.093700 -0.268529 -0.800713  0.077161  0.151046  -0.196323   
329181      1.755562 -0.952268 -1.925226 -1.936021 -0.267079   0.266921   

component        22        23  
0         -0.464553  0.519011  
1         -1.844788  0.194157  
2         -0.731415 -0.127908  
3          0.936693  1.710758  
4          7.845837 -4.778557  
...             ...       ...  
329177     0.654928 -0.154520  
329178    -1.060969  0.003392  
329179     0.644128 -0.161145  
329180    -0.728214 -0.133603  
329181    -0.816415 -0.026238  

[329182 rows x 24 columns]

In [17]:
y_res

0         2
1         2
2         2
3         2
4         3
         ..
329177    3
329178    3
329179    3
329180    3
329181    3
Name: damage_grade, Length: 329182, dtype: int64

In [18]:
np.unique(y_res, return_counts=True)

(array([1, 2, 3]), array([115547, 105920, 107715]))

In [19]:
X_scaled = StandardScaler().fit_transform(X_res.values)
X_scaled

array([[-0.37962375, -0.55579973, -0.35104152, ...,  0.36985039,
        -0.11227734,  0.10541003],
       [-0.60327034, -0.47907732, -0.37780515, ..., -0.66699757,
        -0.42454398,  0.04004621],
       [-0.57476435, -0.49359352, -0.4662596 , ..., -0.04907827,
        -0.17265277, -0.02475646],
       ...,
       [-0.56155   , -0.62659142, -0.49492021, ...,  0.15149114,
         0.13855255, -0.03144419],
       [-0.57107151, -0.5114983 , -0.46521654, ..., -0.05288158,
        -0.17192849, -0.02590242],
       [-0.45984475, -0.67740107, -0.549767  , ...,  0.0603015 ,
        -0.19188324, -0.00429948]])

In [20]:
y_res

0         2
1         2
2         2
3         2
4         3
         ..
329177    3
329178    3
329179    3
329180    3
329181    3
Name: damage_grade, Length: 329182, dtype: int64

In [21]:
y_l = np.array(y_res - 1)
X_l = np.array(X_scaled)
X_train, X_test, y_train, y_test = tts(X_l, y_l, test_size=0.20, random_state=15)

In [31]:
np.save("../data/processed/data.npy", X_l)
np.save("../data/processed/label.npy", y_l)


In [23]:
np.unique(y_train, return_counts=True)

(array([0, 1, 2]), array([92464, 84710, 86171]))

In [24]:
y_test

array([0, 0, 0, ..., 0, 1, 2])

In [25]:
output_size = np.unique(y_l).shape[0]
input_size = X_train.shape[1]

In [26]:
X_test

array([[-0.37888208,  2.66874078,  1.18425689, ..., -0.2731267 ,
         0.02616143, -0.17793195],
       [-0.36362488,  0.70768104,  0.04818605, ..., -0.10213987,
         0.29631929, -0.13398522],
       [-0.57367393, -0.52164249, -0.46792856, ..., -0.05241992,
        -0.17403653, -0.02602054],
       ...,
       [ 1.41482165,  0.89974062, -1.44032726, ...,  0.31475178,
         0.0422726 ,  0.10406311],
       [-0.57517121, -0.51141067, -0.47038341, ..., -0.0491614 ,
        -0.17557475, -0.02531088],
       [-0.35331101,  2.1607683 ,  0.94468907, ..., -2.07825078,
        -1.95840344,  0.45734276]])

In [27]:
sfs = LVQ3(input_size=input_size, output_size=output_size, random_state=201, epoch=3, alpha=0.45, beta=0.25, m=0.2,epsilon=0.25, dMethod="cosine")
# sfs.fit(X_train, y_train)


In [28]:
sfs.weight

array([[-0.7721908 ,  0.49576165,  0.22211879,  0.61938361,  0.42571498,
        -0.71992637, -0.46497624, -0.70479109, -0.54386416, -0.52887653,
         0.38004763, -0.70330436, -0.10878835,  0.40168508, -0.80672271,
         0.76526517,  0.73966457,  0.68918843, -0.45259585,  0.57135909,
         0.40227159, -0.01053901,  0.67267462, -0.19163248],
       [-0.65355399, -0.26919644,  0.99417757, -0.31869126,  0.01075933,
         0.07869494, -0.50132586,  0.62548678, -0.6147153 , -0.83949923,
        -0.81167557, -0.30006911,  0.57106996,  0.36138397, -0.92412115,
        -0.41713174, -0.39254003,  0.96769772, -0.67458425,  0.9241251 ,
         0.4033615 ,  0.41730149,  0.79535607, -0.36764077],
       [-0.39847356,  0.8891353 , -0.81216045,  0.38358714,  0.92204392,
         0.42716702, -0.82714944,  0.83001483, -0.58995581, -0.39107245,
         0.33199011,  0.48099673,  0.64847863,  0.49697567,  0.17048774,
         0.49893068, -0.2547203 , -0.018561  , -0.48622587,  0.62246903,
  

In [29]:
# res = sfs.predict(X_test)
# print(classification_report(res, y_test, zero_division=1))